import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// 1. IMPORTANDO O CHAT (ajuste o caminho se sua pasta estiver em outro lugar)
import { Chat } from "@/components/chat"; 

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Meu Portfólio | Artur", 
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR" // Dica extra: Como seu portfólio é brasileiro, mudei o lang para pt-BR
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
        {/* O conteúdo das páginas vai renderizar aqui */}
        {children} 
        
        {/* 2. O COMPONENTE DO CHAT VEM AQUI */}
        <Chat />
        
      </body>
    </html>
  );
}